### ISSUE TITLE
AssertionError: No. communities (...) differ from no. nodes (...)

### ISSUE THREAD

**Issue by dan-grm** [KrainskiL/CGE.jl#7]
I noticed that for a *0-based* graph with nodes from 0 to n-1,
the script doesn't work properly and throws the following error:

`AssertionError: No. communities (9705) differ from no. nodes (9706)`

I used the script with the command:

`julia CGE_CLI.jl -g graph.edgelist -e ./graph/node_embeddings/node2vec-d-128_l-80_r-18_k-16_e-1_p-1.0_q-1.0/nodes.emb -v`

The verbose output is:
```
2 columns and 27403 rows in edgelist file.
Graph contains 9706 vertices
Done preparing edgelist and vertices weights
0.976024
```

I noticed, that the communities file generated with the Louvain algorithm ends like this:

```
9702 0
9703 1
9704 2
9705 1
```

So the script mistakenly assumes in the Assertion that not all Nodes are assigned to a community,
while this is actually the case because the nodes start at 0.

For me changing the graph to *1-based* solved the problem.
But I guess it would be nice to fix it or at least to mention in the readme that for automatic community generation a 1-based graph is required.

**Comment by KrainskiL** [comment]
Thank you for submitting the issue. Indeed, the implementation was handling the automated clustering generation only for 1-based vertices. For some reason Louvain binary always generated cluster assignment for node '0', even if there is none in the edgelist. After the fix in v2.0.1, clustering function checks how the labelling is set up and modify the output file accordingly.
