### ISSUE TITLE
"Best global external score" and "Best global internal score" are reversed in output

### ISSUE THREAD

**Issue by smithna** [KrainskiL/CGE.jl#8]
When calculating the internal and external scores, x is calculated with the internal mask = true and y is calculated with the internal mask = false.
```
  x = JS(vect_C, vect_B, vect_I, true)
  y = JS(vect_C, vect_B, vect_I, false)
```

When assigning these results to the exported variables, x is assigned to best external and y is assigned to best internal
```
  best_div_ext = !split ? 0.0 : x
  best_div_int = !split ? 0.0 : y
```

I think these should be reversed.

**Comment by KrainskiL** [comment]
Hi,
Thank you for raising the issue. That was the bug indeed. It was fixed both in undirected and directed divergence function.
